spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: authentication-service
            uri: http://localhost:8000
            predicates:
              - Path=/auth/**

          # Uncomment these routes if needed:
          # - id: patient-service
          #   uri: http://localhost:8082
          #   predicates:
          #     - Path=/api/patients/**

          # - id: appointment-service
          #   uri: http://localhost:8083
          #   predicates:
          #     - Path=/api/appointments/**

          - id: DoctorService
            uri: lb://DocterService
            predicates:
              - Path=/doctors/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
